# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext-rmarkdown-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-deseq2=1.30.1
  - r-dplyr=1.0.6
  - r-tidyr=1.1.3
  - r-ggrepel=0.9.1
  - r-scales=1.1.1
  - r-dt=0.18
  - r-forcats=0.5.1
  - r-stringr=1.4.0
  - r-knitr=1.33
  - r-rmarkdown=2.8
  - r-reshape2=1.4.3
  - r-tibble=3.1.2
